### ISSUE TITLE
Triggerable Spawn/Settings

### ISSUE THREAD

**Issue by TheFinalEvent97** [Rearth/NPC_mod#1]
Would it be possible to have the Spawn NPC and NPC Mode settings to be triggered/changed by a timer/sensor etc?

**Comment by Rearth** [comment]
Hey, i just published an update that addresses these issues. You can spawn npcs and toggle the active mode now using actions (in timers, sensors. etc), and also spawn new npc's that way.
To change the npc mode, you'll most likely want to use a programmable block if you want to automate it. With that the custom data of the controller block needs to be updated, the guide for that can be found here:
https://gist.github.com/Rearth/5abd41d9028fd4355423391c38fad5a0

**Comment by TheFinalEvent97** [comment]
Thanks for all your hard work!
